### ISSUE TITLE
No Idea to implement Parallel encoding

### ISSUE THREAD

**Issue by Watch-Video** [sportarchive/CloudTranscode#31]
Have anyone an idea how to implement parallel encoding for video into cloudtranscode ?

My first approach was to implement the splitter into validateInputAndAssetActivity and then let the TranscodeAssetActivity pick them up and merge them on end.

But all doesnt work -.-
Need trusted help

Regards Sascha

**Comment by koxon** [comment]
Hi Sasha,

Are you able to make the transcoding work without your custom code?


Splitting video is a tricky business.
I think it would require an entire new workflow with custom ActivityTasks
for this. That's how I envisioned it.

------

If you want to get started with such an implementation, here is how to
start right.


Look in InputPoller.php: start_job
That function initiate the start of a new workflow. The type of the
workflow is pulled from the config file. Only one workflow can be managed
today but we would need multiple workflows by replacing in the config file:

"cloudTranscode": {
        "workflow": {

by an array

"cloudTranscode": {
        "workflows": [
                "activities": [
        {

The activityList should be associated to the workflow and not outside of
it. As displayed above.

Each workflow would use a different "DecisionTaskList" (Decision task queue
in SWF).

Then when your client submit a job, in the JSON input submitted by the
client we could add a parameter to tell which workflow to use.

In InputPoller.php:start_job we could retrieve the workflow information
from $message.
Then, when calling $swf->startWorkflowExecution we could pass along the
workflow you want to execute.

------

Now if we have multiple workflows, then the Decider.php will need some work
as well.
The domain should be created dynamically when receiving a new DecisionTask
instead of being init in the constructor.

When registering your workflow in the tracker you should provide the
activityList for the workflow you are actually starting.

// Register workflow in tracker if not already register
        $newWorkflow = $this->workflowTracker->register_workflow_in_tracker(
            $workflowExecution,
            *$this->activityList,*
            $workflowInput
        );

Then in *activity_task_completed($event, $taskToken, $workflowExecution)*
*This is where the chain of event happen,* You should implement your logic
for your workflow.

Today this code in the DeciderBrain is very static, and build for handling
a unique workflow. If we have many, we should make the decider and
deciderBrain more modular and load the proper Brain module for the workflow
we are executing.

------

For the split/merge workflow, you would need 4 tasks:
- ValidateInputAndAsset
- SplitVideoAsset
- TranscodeAsset
- MergeVideoAssets

Validate would work as today and check the input file.
The split would take the original input file, split it and upload it in a
TMP folder in S3.
Transcode you take those splits and transcode them and upload them in
another TMP folder. It would delete the TMP splits.
Merge would take all the transcoded files merge them and upload the final
result to S3. Then delete all the TMP transcoded splits.

-------

As I said it's no easy task but I think it would be worth it if you have a
good split/merge algorithm that produce quality videos.

For now I didn't spend my time thinking too much about it and focused on
transcoding one video at a time.

------

Thanks for your interest and don't hesitate to ping me for any questions!

Nicolas


On Sun, Jan 11, 2015 at 10:33 AM, Watch-Video <notifications@github.com>
wrote:

> Have anyone an idea how to implement parallel encoding for video into
> cloudtranscode ?
>
> My first approach was to implement the splitter into
> validateInputAndAssetActivity and then let the TranscodeAssetActivity pick
> them up and merge them on end.
>
> But all doesnt work -.-
> Need trusted help
>
> Regards Sascha
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sportarchive/CloudTranscode/issues/31>.
>



-- 
 Nicolas Menciere

**Comment by Watch-Video** [comment]
Yes without customisation the whole CloudTranscode code works without my code.
But i have seen some strange bugs. 
I will tell about later.
The Parallel part is a really true Brain fucker sometime i can not sleep while im dreaming about how to solve this tricky task.

Regards Sascha

**Comment by Watch-Video** [comment]
I have created a fork.
I would spend the the split and merge algorithms and write the corresponding activitys.
If you can customize the the other parts eg. workflows, client params, updated json_schemas.

For this we must ensure we create a nother repository like CloudTranscodeParallel for multiple encoding and CloudTranscode for One Video per Worker.

Love Sascha

**Comment by koxon** [comment]
I hate when it goes into your dream ...

Report me the bugs if you see some.
I will have a guy to work on Cloud Transcode in the near future for my
business.
It should move forward.

On Mon, Jan 12, 2015 at 2:25 AM, Watch-Video <notifications@github.com>
wrote:

> Yes without customisation the whole CloudTranscode code works without my
> code.
> But i have seen some strange bugs.
> I will tell about later.
> The Parallel part is a really true Brain fucker sometime i can not sleep
> while im dreaming about how to solve this tricky task.
>
> Regards Sascha
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sportarchive/CloudTranscode/issues/31#issuecomment-69536147>
> .
>



-- 
 Nicolas Menciere

**Comment by koxon** [comment]
It would be great if you can implement the activities for split and merge.
I can do the rest. It will take some time to get going on that again but I
will soon have a new hire and I was thinking of making him work on the
project.

No need for multiple repo, we can just have several workflows. I don't want
to start duplicating maintenance.

Split/Merge will be interesting for huge file size and large cluster but
not for smaller scale. Splitting/merge will lengthen the process so you
better win a lot during the transcoding phase.

I would love to implement that though, it would be a huge accomplishment.
Not even Netflix is doing it.

I am in contact with the guy in a Finland University that lead a research
team on the subject.
See his page: http://users.abo.fi/slafond/publication.php
They implemented the split and many other things on the subject. They are
really good.
*Read their publication papers if you implement this:*
http://tucs.fi/publications/view/?id=iJoDeLaJo12a
http://tucs.fi/publications/view/?id=inpJoDeLaLi11a
http://tucs.fi/publications/view/?id=inpAsJoDeLaPoLi13a
http://tucs.fi/publications/view/?id=cJoAsDeLaPoLi13a

This is not an easy for sure ...

I have their Skype contact and I can put you in touch.

Best
Nicolas

On Mon, Jan 12, 2015 at 7:25 AM, Watch-Video <notifications@github.com>
wrote:

> I have created a fork.
> I would spend the the split and merge algorithms and write the
> corresponding activitys.
> If you can customize the the other parts eg. workflows, client params,
> updated json_schemas.
>
> For this we must ensure we create a nother repository like
> CloudTranscodeParallel for multiple encoding and CloudTranscode for One
> Video per Worker.
>
> Love Sascha
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sportarchive/CloudTranscode/issues/31#issuecomment-69562740>
> .
>



-- 
 Nicolas Menciere
